name: Test Matrix Workflow
on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: semgrep/semgrep
    strategy:
      matrix:
        folder: ["folder1", "folder2"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          cd ${{ matrix.folder }}
          export SEMGREP_REPO_DISPLAY_NAME=${{ matrix.folder }}
          semgrep ci
